### ISSUE TITLE
can't find 'perl5db.pl'

### ISSUE THREAD

**Issue by toshirov** [raix/vscode-perl-debug#16]
I'm trying  v0.1.6 on Visual Studio Code 1.9.0 for Mac OS.

I can't debug anything I always get errors of this kind (it happens with lots of modules):

Can't open 'perl5db.pl': File not found (/Users/toshiro/projects/test/ptab/System/Library/Perl/5.18/perl5db.pl).

Obviously, this path does not exist (I think it's joining both the work directory '/Users/toshiro/projects/test/ptab' with the system perl location 'System/Library/Perl/5.18'

**Comment by raix** [comment]
@toshirov can you try to run the perl debug tool from a terminal - just to make sure that works

**Comment by toshirov** [comment]
@raix `perl -d`  works fine from the command line. As I said previously, I think the error is somewhere in the library path definition, it's joining both the current directory with the system perl library path

**Comment by papaiatis** [comment]
Having the same issue here!

**Comment by raix** [comment]
Thanks @toshirov I'll take a look at it - it might be a thing in the debug configuration

**Comment by bigtlb** [comment]
Yes, this happens for me as well, if I try to debug any perl below the root folder of the currently open solution.

> Unable to open 'perl5db.pl': File not found (y:\VM\Source\Grainger\ZipSource\testperf2-20170220\testperf2\Files\adaptors\graingerpricev1\C:\Strawberry\perl\lib\perl5db.pl.

This files debug correctly and breakpoints can be set using `perl -d`.

NOTE:  This only happens when I try to set a breakpoint.  Or when a breakpoint is already set and you start debugging.  If there are no breakpoints set, the debugger starts up correctly and you can step through.

ADDITIONALLY:  This will also happen even in the simplest cases, if the name of the file being debugged starts with 'g', 'k', 'o', 'p'.  I know this sounds weird but I validated with a folder containing only a single perl file, with only 2 lines in it.

```
$a = "hello";
$b = "goodbye";
```

Name the file `a.pl`, and it debugs fine, rename it `g.pl`, and when you try to add a breakpoint and debug, it will blow up with the same message about perl5db.pl not found.

**Comment by raix** [comment]
should be fixed, released in [0.2.0](https://github.com/raix/vscode-perl-debug/releases/tag/v0.2.0) - please reopen if the issue persists
